"""Actionable OpenVINO, device, routing, and model diagnostics for the browser UI."""

from __future__ import annotations

from app import ui_extension

_EXTENSION_ID = "ovllm-system-doctor-extension"

# The CSS and JavaScript are shipped verbatim into the single-file browser client.
# Ruff must not reflow these generated payloads as Python source.
# fmt: off
DOCTOR_CSS = r"""
#doctor-btn{position:relative}#doctor-btn:after{content:'';position:absolute;right:4px;top:4px;width:7px;height:7px;border:2px solid var(--surface-2);border-radius:50%;background:var(--amber);opacity:0}#doctor-btn.has-warning:after,#doctor-btn.has-error:after{opacity:1}#doctor-btn.has-error:after{background:var(--red)}
#doctor-modal .modal-card{width:min(860px,calc(100vw - 28px));max-height:min(900px,calc(100dvh - 28px));overflow:hidden}.doctor-head p{margin-top:3px;color:var(--text-3);font-size:10px}.doctor-body{min-height:0;overflow:auto;padding:18px 20px 20px;overscroll-behavior:contain}.doctor-loading,.doctor-fatal{display:grid;min-height:300px;place-items:center;padding:28px;text-align:center;color:var(--text-2)}.doctor-loading>div{display:flex;flex-direction:column;align-items:center;gap:12px;max-width:380px;line-height:1.5}
.doctor-overview{display:grid;grid-template-columns:minmax(0,1.45fr) repeat(3,minmax(105px,.65fr));gap:9px}.doctor-summary,.doctor-stat,.doctor-check,.doctor-device,.doctor-models{border:1px solid var(--border);background:color-mix(in srgb,var(--surface-2) 76%,transparent)}.doctor-summary{display:flex;align-items:center;gap:12px;padding:14px;border-radius:12px}.doctor-health{display:grid;width:42px;height:42px;flex:0 0 42px;place-items:center;border-radius:12px;background:var(--surface-3);color:var(--text-2)}.doctor-summary.pass .doctor-health{color:var(--green);background:color-mix(in srgb,var(--green) 12%,var(--surface-3))}.doctor-summary.warning .doctor-health{color:var(--amber);background:color-mix(in srgb,var(--amber) 12%,var(--surface-3))}.doctor-summary.error .doctor-health{color:var(--red);background:color-mix(in srgb,var(--red) 12%,var(--surface-3))}.doctor-label{color:var(--text-3);font-size:9px;font-weight:800;letter-spacing:.8px;text-transform:uppercase}.doctor-title{margin-top:3px;color:var(--text-1);font-size:16px;font-weight:740}.doctor-detail{margin-top:3px;color:var(--text-2);font-size:10px;line-height:1.42}.doctor-stat{min-width:0;padding:12px;border-radius:12px}.doctor-stat strong,.doctor-stat small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.doctor-stat strong{margin-top:6px;color:var(--text-1);font-size:13px}.doctor-stat small{margin-top:3px;color:var(--text-3);font-size:9px}
.doctor-section{margin-top:18px}.doctor-section-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-end;margin-bottom:9px}.doctor-section-head h4{font-size:12px;color:var(--text-1)}.doctor-section-head span{font-size:9.5px;color:var(--text-3);text-align:right}.doctor-checks{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.doctor-check{display:grid;grid-template-columns:24px minmax(0,1fr);gap:9px;padding:11px;border-radius:11px}.doctor-marker{display:grid;width:24px;height:24px;place-items:center;border-radius:8px;background:var(--surface-3);color:var(--text-3);font-size:12px;font-weight:800}.doctor-check.pass .doctor-marker{color:var(--green);background:color-mix(in srgb,var(--green) 12%,var(--surface-3))}.doctor-check.warning .doctor-marker{color:var(--amber);background:color-mix(in srgb,var(--amber) 12%,var(--surface-3))}.doctor-check.error .doctor-marker{color:var(--red);background:color-mix(in srgb,var(--red) 12%,var(--surface-3))}.doctor-check h5{font-size:10.5px;color:var(--text-1)}.doctor-check p{margin-top:3px;font-size:9.5px;line-height:1.42;color:var(--text-2)}.doctor-next{margin-top:5px!important;color:var(--text-3)!important}.doctor-next strong{color:var(--text-2)}
.doctor-devices{display:flex;flex-wrap:wrap;gap:7px}.doctor-device{padding:8px 10px;border-radius:9px;min-width:120px}.doctor-device strong,.doctor-device span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.doctor-device strong{font-size:10.5px;color:var(--text-1)}.doctor-device span{max-width:250px;margin-top:2px;font-size:9px;color:var(--text-3)}.doctor-models{overflow:hidden;border-radius:11px}.doctor-model-scroll{overflow-x:auto}.doctor-row{display:grid;grid-template-columns:minmax(170px,1.5fr) minmax(100px,.7fr) minmax(120px,.8fr) minmax(160px,1fr);gap:10px;align-items:center;min-width:670px;padding:10px 12px;border-bottom:1px solid var(--border)}.doctor-row:last-child{border:0}.doctor-row.header{background:var(--surface-2);color:var(--text-3);font-size:9px;font-weight:800;letter-spacing:.6px;text-transform:uppercase}.doctor-model-name,.doctor-model-note{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.doctor-model-name{font-size:10.5px;font-weight:700;color:var(--text-1)}.doctor-model-name small{display:block;margin-top:2px;font-size:8.5px;font-weight:400;color:var(--text-3)}.doctor-model-note{font-size:9px;color:var(--text-2)}.doctor-pill{display:inline-flex;max-width:100%;padding:3px 7px;border:1px solid var(--border);border-radius:999px;font-size:9px;font-weight:700;color:var(--text-2)}.doctor-pill.pass{color:var(--green);border-color:color-mix(in srgb,var(--green) 35%,var(--border))}.doctor-pill.warning{color:var(--amber);border-color:color-mix(in srgb,var(--amber) 38%,var(--border))}.doctor-pill.error{color:var(--red);border-color:color-mix(in srgb,var(--red) 40%,var(--border))}.doctor-empty{padding:20px;text-align:center;color:var(--text-3);font-size:10px}
.doctor-footer{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px 20px calc(12px + env(safe-area-inset-bottom));border-top:1px solid var(--border);background:var(--surface-1)}.doctor-footer-note{font-size:9px;line-height:1.35;color:var(--text-3)}.doctor-actions{display:flex;gap:8px;flex:0 0 auto}.doctor-action{min-height:36px;padding:7px 12px;border:1px solid var(--border);border-radius:9px;background:var(--surface-2);color:var(--text-1);font:inherit;font-size:10px;font-weight:700;cursor:pointer}.doctor-action:hover:not(:disabled){border-color:var(--primary);background:var(--surface-3)}.doctor-action.primary{background:var(--primary);border-color:transparent;color:white}.doctor-action:disabled{opacity:.55;cursor:not-allowed}
@media(max-width:760px){#doctor-modal .modal-card{width:calc(100vw - 16px);max-height:calc(100dvh - 16px)}.doctor-body{padding:14px}.doctor-overview{grid-template-columns:repeat(3,minmax(0,1fr))}.doctor-summary{grid-column:1/-1}.doctor-checks{grid-template-columns:1fr}.doctor-footer{align-items:stretch;flex-direction:column;padding:11px 14px calc(11px + env(safe-area-inset-bottom))}.doctor-actions{display:grid;grid-template-columns:1fr 1fr}.doctor-action{min-height:44px}}@media(max-width:460px){.doctor-overview{grid-template-columns:1fr}.doctor-summary{grid-column:auto}.doctor-stat{display:flex;align-items:center;justify-content:space-between;gap:10px}.doctor-stat strong{margin:0;text-align:right}.doctor-stat small{display:none}.doctor-actions{grid-template-columns:1fr}}
"""

DOCTOR_JS = r"""
(() => {
'use strict';
if(window.__ovllmSystemDoctorInstalled)return;window.__ovllmSystemDoctorInstalled=true;
const header=document.querySelector('.header-right');if(!header)return;
const icon='<svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M12 2v4"/><path d="M8 4h8"/><path d="M9 6v5a3 3 0 0 0 6 0V6"/><path d="M12 14v2a4 4 0 0 0 4 4h1"/><circle cx="19" cy="20" r="2"/></svg>';
const trigger=document.createElement('button');trigger.type='button';trigger.id='doctor-btn';trigger.className='icon-btn';trigger.title='Open System Doctor';trigger.setAttribute('aria-label','Open System Doctor diagnostics');trigger.innerHTML=icon;header.insertBefore(trigger,document.getElementById('settings-toggle-btn'));
const modal=document.createElement('div');modal.id='doctor-modal';modal.className='modal-overlay hidden';modal.setAttribute('aria-hidden','true');modal.innerHTML=`<div class="modal-card" role="dialog" aria-modal="true" aria-labelledby="doctor-title" aria-describedby="doctor-subtitle"><div class="modal-header"><div class="doctor-head"><h3 id="doctor-title">System Doctor</h3><p id="doctor-subtitle">OpenVINO runtime, hardware, routing, model, memory, and disk checks</p></div><button type="button" id="doctor-close" class="close-btn" aria-label="Close System Doctor">&times;</button></div><div class="doctor-body" id="doctor-body"></div><div class="doctor-footer"><span class="doctor-footer-note">Support reports exclude API keys, prompts, chat content, and local directory paths.</span><div class="doctor-actions"><button type="button" class="doctor-action" id="doctor-copy">Copy support report</button><button type="button" class="doctor-action primary" id="doctor-refresh">Run checks again</button></div></div></div>`;document.body.appendChild(modal);
const body=modal.querySelector('#doctor-body'),closeBtn=modal.querySelector('#doctor-close'),copyBtn=modal.querySelector('#doctor-copy'),refreshBtn=modal.querySelector('#doctor-refresh');let returnFocus=null,controller=null,report=null;
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
const gb=v=>Number.isFinite(Number(v))?`${Number(v).toFixed(Number(v)>=10?0:1)} GB`:'Unknown';
const base=v=>String(v||'').trim().toUpperCase().split('.')[0];
const fallback=v=>/^(AUTO|MULTI|HETERO)(:|$)/i.test(String(v||''));
function headers(){let key='';try{key=localStorage.getItem('ovllm.apikey.v1')||''}catch{}return key?{Authorization:`Bearer ${key}`}:{ };}
function expressionAvailable(value,available){const target=String(value||'').trim().toUpperCase();if(!target||target==='AUTO')return true;const set=new Set(available.map(base));const list=target.includes(':')?target.split(':')[1].split(','):[target];return list.every(item=>set.has(base(item)));}
const mk=(id,level,title,detail,action='')=>({id,level,title,detail,action});
function modelState(m){if(m._doctorMock)return['warning','Simulated'];if(m.status==='error')return['error','Error'];if(m.is_loading)return['warning',m.status_label||'Preparing'];if(m.is_loaded)return['pass','Loaded'];if(m.is_downloaded)return['pass','Converted'];return['warning','Not converted'];}
function diagnose(status,devices){
 const available=Array.isArray(devices.available)?devices.available:[],details=Array.isArray(devices.devices)?devices.devices:[],models=Array.isArray(status.models?.available)?status.models.available:[];
 const mock=devices.mock===true;models.forEach(m=>m._doctorMock=mock);const loaded=models.filter(m=>m.is_loaded),converted=models.filter(m=>m.is_downloaded&&!mock),failed=models.filter(m=>m.status==='error'),bases=new Set(available.map(base));
 const npu=bases.has('NPU'),runtime=devices.openvino_available===true&&!mock,target=document.getElementById('device-select')?.value||status.device?.default||devices.default_device||'NPU';
 const routes=loaded.map(m=>m.device).filter(Boolean),fallbackRoutes=[...new Set(routes.filter(fallback))],explicit=[...new Set(routes.filter(v=>!fallback(v)))],ram=Number(status.memory?.available_gb||0),totalRam=Number(status.memory?.total_gb||0),disk=Number(status.disk?.free_gb||0),checks=[];
 checks.push(mk('server','pass','Local server is reachable','System status and device discovery both responded.'));
 checks.push(runtime?mk('runtime','pass','OpenVINO GenAI is active','Real OpenVINO inference is available; mock mode is off.'):mock?mk('runtime','warning','Mock engine is active','The UI works, but requests are not using OpenVINO hardware inference.','Install the project runtime dependencies and restart without OV_LLM_MOCK.'):mk('runtime','error','OpenVINO GenAI is unavailable','The server did not detect the OpenVINO GenAI runtime.','Install the project dependencies and restart the server.'));
 const npuInfo=details.find(d=>base(d.device)==='NPU');checks.push(npu?mk('npu','pass','NPU is visible to OpenVINO',npuInfo?.full_name?`${npuInfo.device}: ${npuInfo.full_name}`:'The OpenVINO device plugin reports an NPU.'):mk('npu','warning','NPU is not visible','OpenVINO did not report an NPU. The machine may not have a supported NPU, or its Intel NPU driver/plugin may be missing or outdated.','On supported Intel Core Ultra hardware, update the Intel NPU driver, reboot, verify Device Manager, and run these checks again.'));
 checks.push(available.length?mk('devices','pass',`${available.length} OpenVINO device${available.length===1?'':'s'} detected`,available.join(', ')):mk('devices','error','No OpenVINO devices were detected','The runtime could not enumerate CPU, GPU, or NPU plugins.','Confirm the OpenVINO installation and hardware drivers, then restart.'));
 checks.push(expressionAvailable(target,available)?mk('target','pass',`Selected load target: ${target}`,'The target matches the detected device inventory.'):mk('target','warning',`Selected target ${target} is not fully available`,`Detected devices: ${available.join(', ')||'none'}.`,'Choose a detected device or repair the missing driver/plugin.'));
 checks.push(fallbackRoutes.length?mk('routing','warning',`Fallback routing active: ${fallbackRoutes.join(', ')}`,'OpenVINO may choose among listed devices; priority order is not proof of exact physical execution.','Use explicit NPU, GPU, or CPU when strict placement matters.'):explicit.length?mk('routing','pass',`Explicit device routing: ${explicit.join(', ')}`,'Loaded models use explicit targets rather than AUTO/MULTI/HETERO fallback.'):mk('routing','info','No active inference route','Load a converted model to verify its runtime route.'));
 checks.push(converted.length?mk('conversion','pass',`${converted.length} model${converted.length===1?'':'s'} converted`,`${converted.length} of ${models.length} catalog models have local OpenVINO IR files.`):mk('conversion','warning',mock?'Conversion state is simulated in mock mode':'No model has been converted yet',mock?'Mock mode does not verify whether local OpenVINO IR files exist.':'No local OpenVINO IR is ready to load.',mock?'Restart with OpenVINO enabled to verify actual model files.':'Choose a small model and use Convert & Load.'));
 checks.push(loaded.length?mk('loaded',mock?'warning':'pass',`${loaded.length} model${loaded.length===1?'':'s'} ${mock?'simulated':'loaded'}`,loaded.map(m=>`${m.name} on ${m.device||'unknown'}`).join('; ')):mk('loaded','info','No model is loaded','A converted model must be loaded before chat inference can run.'));
 if(failed.length)checks.push(mk('errors','error',`${failed.length} model preparation error${failed.length===1?'':'s'}`,`${failed.map(m=>m.name||m.id).join(', ')} failed preparation.`,'Open the model row for the reported error, repair the dependency/device issue, then retry.'));
 checks.push(!ram?mk('memory','info','Memory telemetry unavailable','The server could not report available system memory.'):ram<2?mk('memory','error',`Only ${gb(ram)} RAM available`,`System total: ${gb(totalRam)}.`,'Close heavy applications or load a smaller INT4 model.'):ram<6?mk('memory','warning',`${gb(ram)} RAM available`,`System total: ${gb(totalRam)}. Larger models may page heavily.`,'Prefer a smaller INT4 model and shorter context.'):mk('memory','pass',`${gb(ram)} RAM available`,`System total: ${gb(totalRam)}.`));
 checks.push(!disk?mk('disk','info','Disk telemetry unavailable','The server could not report free space for the model volume.'):disk<3?mk('disk','error',`Only ${gb(disk)} disk space free`,'Conversion needs temporary space in addition to final files.','Free disk space or move OV_LLM_MODELS_DIR.'):disk<12?mk('disk','warning',`${gb(disk)} disk space free`,'A larger conversion may exceed remaining capacity.','Free space before preparing larger models.'):mk('disk','pass',`${gb(disk)} disk space free`,`${gb(status.disk?.models_gb||0)} used by converted models.`));
 const errors=checks.filter(c=>c.level==='error').length,warnings=checks.filter(c=>c.level==='warning').length,overall=errors?'error':warnings?'warning':'pass';
 return{generatedAt:new Date().toISOString(),overall,errors,warnings,title:errors?'Action required':warnings?'Usable, with warnings':'System looks ready',detail:errors?`${errors} blocking issue${errors===1?'':'s'} and ${warnings} warning${warnings===1?'':'s'} found.`:warnings?`${warnings} warning${warnings===1?'':'s'} found. Review them before relying on NPU execution.`:'Runtime, device, model, memory, and disk checks passed.',runtime,mock,available,details,npu,target,fallbackRoutes,models,converted:converted.length,loaded:loaded.length,ram,totalRam,disk,modelDisk:Number(status.disk?.models_gb||0),checks};
}
const marker=l=>l==='pass'?'✓':l==='info'?'i':'!';
function checkHtml(c){return`<article class="doctor-check ${esc(c.level)}"><span class="doctor-marker" aria-hidden="true">${marker(c.level)}</span><div><h5>${esc(c.title)}</h5><p>${esc(c.detail)}</p>${c.action?`<p class="doctor-next"><strong>Next step:</strong> ${esc(c.action)}</p>`:''}</div></article>`;}
function modelHtml(m){const [level,state]=modelState(m),route=m.is_loaded?(m.device||'Unknown device'):(m.recommended_device?`Recommended: ${m.recommended_device}`:'No recommendation'),note=m._doctorMock?'Mock mode does not verify local OpenVINO IR':m.status==='error'?(m.error||m.status_label||'Preparation failed'):m.is_loading?(m.progress?.message||m.status_label||'Preparing model'):m.is_downloaded?'Local OpenVINO IR is ready':m.source_model?'Conversion required before loading':'No conversion source configured';return`<div class="doctor-row"><div class="doctor-model-name" title="${esc(m.name||m.id)}">${esc(m.name||m.id)}<small>${esc(m.id)} · ${esc((m.weight_format||'unknown').toUpperCase())}</small></div><div><span class="doctor-pill ${level}">${esc(state)}</span></div><div><span class="doctor-pill ${m.is_loaded?'pass':''}">${esc(route)}</span></div><div class="doctor-model-note" title="${esc(note)}">${esc(note)}</div></div>`;}
function render(r){const devices=r.details.length?r.details.map(d=>`<div class="doctor-device"><strong>${esc(d.device)}</strong><span title="${esc(d.full_name)}">${esc(d.full_name||d.device)}</span></div>`).join(''):'<div class="doctor-device"><strong>No devices</strong><span>OpenVINO returned an empty inventory.</span></div>';const models=r.models.length?`<div class="doctor-model-scroll"><div class="doctor-row header"><span>Model</span><span>State</span><span>Route</span><span>Diagnostic</span></div>${r.models.map(modelHtml).join('')}</div>`:'<div class="doctor-empty">The model catalog is empty.</div>';body.innerHTML=`<section class="doctor-overview" aria-label="Diagnostic summary"><div class="doctor-summary ${r.overall}"><span class="doctor-health" aria-hidden="true">${icon}</span><div><div class="doctor-label">Overall health</div><div class="doctor-title">${esc(r.title)}</div><div class="doctor-detail">${esc(r.detail)}</div></div></div><div class="doctor-stat"><span class="doctor-label">NPU</span><strong>${r.npu?'Visible':'Not visible'}</strong><small>OpenVINO inventory</small></div><div class="doctor-stat"><span class="doctor-label">Models</span><strong>${r.mock?'Simulated':`${r.converted}/${r.models.length} converted`}</strong><small>${r.loaded} ${r.mock?'simulated':'loaded'}</small></div><div class="doctor-stat"><span class="doctor-label">Routing</span><strong>${r.fallbackRoutes.length?'Fallback active':r.loaded?'Explicit':'Inactive'}</strong><small title="${esc(r.target)}">Target: ${esc(r.target)}</small></div></section><section class="doctor-section"><div class="doctor-section-head"><h4>Checks and remediation</h4><span>${r.checks.length} checks · ${r.errors} errors · ${r.warnings} warnings</span></div><div class="doctor-checks">${r.checks.map(checkHtml).join('')}</div></section><section class="doctor-section"><div class="doctor-section-head"><h4>Detected OpenVINO devices</h4><span>${esc(r.available.join(', ')||'none detected')}</span></div><div class="doctor-devices">${devices}</div></section><section class="doctor-section"><div class="doctor-section-head"><h4>Model readiness</h4><span>Converted means local OpenVINO IR is present</span></div><div class="doctor-models">${models}</div></section>`;}
function fail(error){report=null;trigger.className='icon-btn has-error';body.innerHTML=`<div class="doctor-fatal"><div><div class="doctor-title">The local server could not be diagnosed</div><div class="doctor-detail">${esc(error.message||'Connection failed.')}</div><p class="doctor-next"><strong>Next step:</strong> Confirm the process is running, verify the API key in Settings, then retry.</p></div></div>`;}
async function run(){controller?.abort();controller=new AbortController();refreshBtn.disabled=true;refreshBtn.textContent='Running checks…';copyBtn.disabled=true;body.innerHTML='<div class="doctor-loading"><div><span class="spinner"></span><span>Checking OpenVINO, drivers, devices, routes, model files, memory, and disk…</span></div></div>';try{const h=headers(),responses=await Promise.all([fetch('/v1/system/status',{headers:h,signal:controller.signal}),fetch('/v1/devices',{headers:h,signal:controller.signal})]);if(responses.some(r=>r.status===401))throw new Error('A valid API key is required. Open Settings and enter it before retrying.');if(!responses[0].ok)throw new Error(`System status failed with HTTP ${responses[0].status}.`);if(!responses[1].ok)throw new Error(`Device discovery failed with HTTP ${responses[1].status}.`);const data=await Promise.all(responses.map(r=>r.json()));report=diagnose(data[0],data[1]);render(report);trigger.classList.toggle('has-error',report.overall==='error');trigger.classList.toggle('has-warning',report.overall==='warning');trigger.title=report.overall==='pass'?'System Doctor: all checks passed':`System Doctor: ${report.errors} errors, ${report.warnings} warnings`;copyBtn.disabled=false}catch(error){if(error.name!=='AbortError')fail(error)}finally{refreshBtn.disabled=false;refreshBtn.textContent='Run checks again'}}
function text(r){return['# OpenVINO LLM Support Report',`Generated: ${r.generatedAt}`,`Overall: ${r.title}`,`OpenVINO runtime: ${r.runtime?'active':r.mock?'mock engine active':'unavailable'}`,`Detected devices: ${r.available.join(', ')||'none'}`,`NPU visible: ${r.npu?'yes':'no'}`,`Selected load target: ${r.target}`,`Fallback routing active: ${r.fallbackRoutes.length?r.fallbackRoutes.join(', '):'no'}`,`RAM: ${gb(r.ram)} available / ${gb(r.totalRam)} total`,`Disk: ${gb(r.disk)} free; ${gb(r.modelDisk)} used by converted models`,`Models: ${r.mock?'conversion state simulated':`${r.converted}/${r.models.length} converted`}; ${r.loaded} ${r.mock?'simulated':'loaded'}`,'','## Checks',...r.checks.map(c=>`- [${c.level.toUpperCase()}] ${c.title}: ${c.detail}${c.action?` Next step: ${c.action}`:''}`),'','## Models',...r.models.map(m=>{const[,state]=modelState(m);return`- ${m.name||m.id} (${m.id}): ${state}; route=${m.is_loaded?(m.device||'unknown'):(m.recommended_device||'not loaded')}; format=${m.weight_format||'unknown'}`}),'','Privacy: API keys, prompts, chat content, model errors, and local directory paths are excluded.'].join('\n')}
async function copy(value){if(navigator.clipboard?.writeText)try{await navigator.clipboard.writeText(value);return}catch{}const field=document.createElement('textarea');field.value=value;field.setAttribute('readonly','');field.style.cssText='position:fixed;left:-9999px;opacity:0';document.body.appendChild(field);field.select();const ok=document.execCommand('copy');field.remove();if(!ok)throw new Error('Clipboard unavailable')}
function focusables(){return[...modal.querySelectorAll('button:not(:disabled),[href],input:not(:disabled),select:not(:disabled),textarea:not(:disabled),[tabindex]:not([tabindex="-1"])')].filter(el=>el.getClientRects().length)}
function open(value){modal.classList.toggle('hidden',!value);modal.setAttribute('aria-hidden',String(!value));document.getElementById('app')?.toggleAttribute('inert',value);if(value){returnFocus=document.activeElement;closeBtn.focus();void run()}else{controller?.abort();if(returnFocus instanceof HTMLElement)returnFocus.focus();returnFocus=null}}
trigger.addEventListener('click',()=>open(true));closeBtn.addEventListener('click',()=>open(false));refreshBtn.addEventListener('click',run);modal.addEventListener('pointerdown',e=>{if(e.target===modal)open(false)});copyBtn.addEventListener('click',async()=>{if(!report)return;copyBtn.disabled=true;try{await copy(text(report));copyBtn.textContent='Copied';if(typeof showToast==='function')showToast('Support report copied','success')}catch(error){if(typeof showToast==='function')showToast(`Copy failed: ${error.message}`,'error')}finally{setTimeout(()=>{copyBtn.textContent='Copy support report';copyBtn.disabled=!report},1400)}});modal.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();open(false);return}if(e.key!=='Tab')return;const list=focusables();if(!list.length)return;const first=list[0],last=list[list.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}});
})();
"""
# fmt: on


def install_system_doctor_extension() -> None:
    """Compose the System Doctor into the bundled single-file browser client."""

    if getattr(ui_extension, "_SYSTEM_DOCTOR_EXTENSION_INSTALLED", False):
        return
    previous_inject = ui_extension.inject_multimodal_ui

    def inject_with_system_doctor(html: str) -> str:
        html = previous_inject(html)
        if f'id="{_EXTENSION_ID}"' in html:
            return html
        payload = (
            f'\n<style id="{_EXTENSION_ID}-styles">\n{DOCTOR_CSS}\n</style>\n'
            f'<script id="{_EXTENSION_ID}">\n{DOCTOR_JS}\n</script>\n'
        )
        if "</body>" in html:
            return html.replace("</body>", f"{payload}</body>", 1)
        return html + payload

    ui_extension.inject_multimodal_ui = inject_with_system_doctor
    ui_extension._SYSTEM_DOCTOR_EXTENSION_INSTALLED = True
